In [1]:
import dgl

C:\Users\awast\anaconda3\envs\nlp\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Using backend: pytorch


In [2]:
import numpy as np
import tensorflow as tf

In [3]:
def make_graph1():
    src=[]
    end=[]
    for i in range(25):
        for j in range(25):
            src.append(i)
            end.append(j)
    g= dgl.graph((np.array(src),np.array(end)),num_nodes=25)
    return g

In [4]:
g=make_graph1()

In [5]:
g.srcnodes()


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])

In [6]:
# g.num_edges()

In [7]:
x_train0=np.load("C:\\Users\\awast\\Desktop\\NLP\\distilbert_single\\distil_train.npy",allow_pickle=True)
x_dev0=np.load("C:\\Users\\awast\\Desktop\\NLP\\distilbert_single\\distil_dev.npy", allow_pickle=True)
x_test0=np.load("C:\\Users\\awast\\Desktop\\NLP\\distilbert_single\\distil_test.npy", allow_pickle=True)

In [8]:
# train_emb=np.load("C:\\Users\\awast\\Desktop\\NLP\\CJPE-main\\Models\\Sequential_Models\\train_embedding.npy",allow_pickle=True)
# dev_emb=np.load("C:\\Users\\awast\\Desktop\\NLP\\CJPE-main\\Models\\Sequential_Models\\dev_embedding.npy",allow_pickle=True)
# test_emb=np.load("C:\\Users\\awast\\Desktop\\NLP\\CJPE-main\\Models\\Sequential_Models\\test_emb.npy",allow_pickle=True)

In [9]:
# train_emb[0].shape

In [10]:
#### x_train0[0].shape[0]

In [11]:
# test_emb[4]

In [12]:
import os
os.environ['DGLBACKEND']='pytorch'

In [13]:
def make_embeddings(train0, dev0, test0):
    train=[]
    dev=[]
    test=[]
    for i in range(train0.shape[0]):
        emb=np.zeros((25,768))
        numb=train0[i].shape[0]
        for j in range(train0[i].shape[0]):
            emb[j]=train0[i][j]
        train.append(emb)
    
    for i in range(dev0.shape[0]):
        emb=np.zeros((25,768))
        numb=dev0[i].shape[0]
        for j in range(dev0[i].shape[0]):
#             emb[j]=train0[i][j][0][0]    
            emb[j]=dev0[i][j]
        dev.append(emb)
    
    for i in range(test0.shape[0]):
        emb=np.zeros((25,768))
        numb=test0[i].shape[0]
        for j in range(test0[i].shape[0]):
#             emb[j]=train0[i][j][0][0]    
#             emb[j]=dev0[i][j][0][0]    
            emb[j]=test0[i][j] 
        test.append(emb)
    
    
    
    return np.array(train), np.array(dev), np.array(test)

In [14]:
# train, dev, test=make_embeddings(train_emb,dev_emb,test_emb)
train, dev, test=make_embeddings(x_train0,x_dev0,x_test0)

In [15]:
# g=g.to('cpu')


In [16]:
import torch

In [17]:
# g.ndata['features']=torch.from_numpy(train)

In [18]:
# g.ndata['features'][0]

In [19]:
train[4].shape

(25, 768)

In [20]:
import kgcnn

In [21]:
import dgl.data

In [22]:
import urllib.request
import pandas as pd

In [23]:
import dgl
from dgl.data import DGLDataset
import torch
import os

In [24]:
# urllib.request.urlretrieve(
#     'https://data.dgl.ai/tutorial/dataset/graph_edges.csv', './graph_edges.csv')
# urllib.request.urlretrieve(
#     'https://data.dgl.ai/tutorial/dataset/graph_properties.csv', './graph_properties.csv')
# edges = pd.read_csv('./graph_edges.csv')
# properties = pd.read_csv('./graph_properties.csv')

# edges.head()

# properties.head()



In [25]:
def make_dataset(x_train0):
    data1={'graph_id':[],'src':[],'dst':[]}
    data= pd.DataFrame(data1)
    x=[]
    y=[]
    z=[]
    for i in range(x_train0.shape[0]):
        #print(i)
        for j in range(25):
            for k in range(25):
                x.append(i)
                y.append(j)
                z.append(k)
                #data = data.append(df2, ignore_index = True)
                #data.loc[len(data.index)] = [i, j, k]
                
    data = {'graph_id': x, 'src': y, 'dst': z}
    data=pd.DataFrame(data)
    
    return data 

In [26]:
train_graph=make_dataset(train)
test_graph=make_dataset(test)


In [27]:
df = pd.read_csv("C:\\Users\\awast\\Desktop\\NLP\\Data\\Data\\ILDC_single\\ILDC_single\\ILDC_single.csv\\ILDC_single.csv")
train_set = df.query(" split=='train' ")
validation_set = df.query(" split=='dev' ")
test_set = df.query(" split=='test' ")

In [28]:
test_set['label']

5082    1
5083    0
5084    0
5085    0
5086    1
       ..
6594    1
6595    0
6596    1
6597    1
6598    1
Name: label, Length: 1517, dtype: int64

In [29]:
def make_dataset_labels(train_set):
    x=[]
    y=[]
    z=[]
    for i in range(train_set.shape[0]):
        #print(i)
        
        x.append(i)
        y.append(train_set['label'][i])
        z.append(25)
                #data = data.append(df2, ignore_index = True)
                #data.loc[len(data.index)] = [i, j, k]
                
    properties = {'graph_id': x, 'label': y, 'num_nodes': z}
    properties=pd.DataFrame(properties)
    return properties

In [30]:
train_properties=make_dataset_labels(train_set)
# 

In [31]:
def make_dataset_labels(test_set):
    x=[]
    y=[]
    z=[]
    for i in range(test_set.shape[0]):
        #print(i)
        
        x.append(i)
        y.append(test_set['label'][i+5082])
        z.append(25)
                #data = data.append(df2, ignore_index = True)
                #data.loc[len(data.index)] = [i, j, k]
                
    properties = {'graph_id': x, 'label': y, 'num_nodes': z}
    properties=pd.DataFrame(properties)
    return properties

In [32]:
test_properties=make_dataset_labels(test_set)

In [33]:
class SyntheticDataset(DGLDataset):
    def __init__(self):
        super().__init__(name='synthetic')
        

    def process(self):
        edges = train_graph
        properties = train_properties
        self.graphs = []
        self.labels = []

        # Create a graph for each graph ID from the edges table.
        # First process the properties table into two dictionaries with graph IDs as keys.
        # The label and number of nodes are values.
        label_dict = {}
        num_nodes_dict = {}
        for _, row in properties.iterrows():
            label_dict[row['graph_id']] = row['label']
            num_nodes_dict[row['graph_id']] = row['num_nodes']

        # For the edges, first group the table by graph IDs.
        edges_group = edges.groupby('graph_id')

        # For each graph ID...
        for graph_id in edges_group.groups:
            # Find the edges as well as the number of nodes and its label.
            edges_of_id = edges_group.get_group(graph_id)
            src = edges_of_id['src'].to_numpy()
            dst = edges_of_id['dst'].to_numpy()
            num_nodes = num_nodes_dict[graph_id]
            label = label_dict[graph_id]

            # Create a graph and add it to the list of graphs and labels.
            g = dgl.graph((src, dst), num_nodes=num_nodes)
            g.ndata['feat']=torch.from_numpy(train[graph_id])      #torch.from_numpy(train[graph_id])
            self.graphs.append(g)
            self.labels.append(label)

        # Convert the label list to tensor for saving.
        self.labels = torch.LongTensor(self.labels)

    def __getitem__(self, i):
        return self.graphs[i], self.labels[i]

    def __len__(self):
        return len(self.graphs)



In [34]:
train_dataset = SyntheticDataset()


# graph, label = dataset[0]
# print(graph, label)

In [35]:
class SyntheticDataset2(DGLDataset):
    def __init__(self):
       #super().__init__(name='synthetic')
        super().__init__(name="new_dataset")
        

    def process(self):
        edges = test_graph
        properties = test_properties
        self.graphs = []
        self.labels = []

        # Create a graph for each graph ID from the edges table.
        # First process the properties table into two dictionaries with graph IDs as keys.
        # The label and number of nodes are values.
        label_dict = {}
        num_nodes_dict = {}
        for _, row in properties.iterrows():
            label_dict[row['graph_id']] = row['label']
            num_nodes_dict[row['graph_id']] = row['num_nodes']

        # For the edges, first group the table by graph IDs.
        edges_group = edges.groupby('graph_id')

        # For each graph ID...
        for graph_id in edges_group.groups:
            # Find the edges as well as the number of nodes and its label.
            edges_of_id = edges_group.get_group(graph_id)
            src = edges_of_id['src'].to_numpy()
            dst = edges_of_id['dst'].to_numpy()
            num_nodes = num_nodes_dict[graph_id]
            label = label_dict[graph_id]

            # Create a graph and add it to the list of graphs and labels.
            g = dgl.graph((src, dst), num_nodes=num_nodes)
            g.ndata['feat']=torch.from_numpy(test[graph_id])
            self.graphs.append(g)
            self.labels.append(label)

        # Convert the label list to tensor for saving.
        self.labels = torch.LongTensor(self.labels)

    def __getitem__(self, i):
        return self.graphs[i], self.labels[i]

    def __len__(self):
        return len(self.graphs)


In [36]:
test_dataset= SyntheticDataset2()

In [37]:
test_dataset.graphs

[Graph(num_nodes=25, num_edges=625,
       ndata_schemes={'feat': Scheme(shape=(768,), dtype=torch.float64)}
       edata_schemes={}),
 Graph(num_nodes=25, num_edges=625,
       ndata_schemes={'feat': Scheme(shape=(768,), dtype=torch.float64)}
       edata_schemes={}),
 Graph(num_nodes=25, num_edges=625,
       ndata_schemes={'feat': Scheme(shape=(768,), dtype=torch.float64)}
       edata_schemes={}),
 Graph(num_nodes=25, num_edges=625,
       ndata_schemes={'feat': Scheme(shape=(768,), dtype=torch.float64)}
       edata_schemes={}),
 Graph(num_nodes=25, num_edges=625,
       ndata_schemes={'feat': Scheme(shape=(768,), dtype=torch.float64)}
       edata_schemes={}),
 Graph(num_nodes=25, num_edges=625,
       ndata_schemes={'feat': Scheme(shape=(768,), dtype=torch.float64)}
       edata_schemes={}),
 Graph(num_nodes=25, num_edges=625,
       ndata_schemes={'feat': Scheme(shape=(768,), dtype=torch.float64)}
       edata_schemes={}),
 Graph(num_nodes=25, num_edges=625,
       ndata_scheme

In [38]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [39]:
test_dataset[0][0].ndata['feat'].shape

torch.Size([25, 768])

In [40]:
"""Torch Module for DenseGraphConv"""
# pylint: disable= no-member, arguments-differ, invalid-name
import torch as th
from torch import nn
from torch.nn import init



# [docs]
class DenseGraphConv1(nn.Module):
    

    def __init__(self,
                 in_feats,
                 out_feats,
                 norm='both',
                 bias=True,
                 activation=None):
        super().__init__()
        self._in_feats = in_feats
        self._out_feats = out_feats
        self._norm = norm
        self.weight = nn.Parameter(th.Tensor(in_feats, out_feats))
        if bias:
            self.bias = nn.Parameter(th.Tensor(out_feats))
        else:
            self.register_buffer('bias', None)

        self.reset_parameters()
        self._activation = activation


# [docs]
    def reset_parameters(self):
        """Reinitialize learnable parameters."""
        init.xavier_uniform_(self.weight)
        if self.bias is not None:
            init.zeros_(self.bias)



# [docs]
    def forward(self, adj, feat):
        r"""Compute (Dense) Graph Convolution layer.

        Parameters
        ----------
        adj : torch.Tensor
            The adjacency matrix of the graph to apply Graph Convolution on, when
            applied to a unidirectional bipartite graph, ``adj`` should be of shape
            should be of shape :math:`(N_{out}, N_{in})`; when applied to a homo
            graph, ``adj`` should be of shape :math:`(N, N)`. In both cases,
            a row represents a destination node while a column represents a source
            node.
        feat : torch.Tensor
            The input feature.

        Returns
        -------
        torch.Tensor
            The output feature of shape :math:`(N, D_{out})` where :math:`D_{out}`
            is size of output feature.
        """
        adj = adj.to(feat.device)
        src_degrees = adj.sum(dim=0).clamp(min=1).double()
        dst_degrees = adj.sum(dim=1).clamp(min=1).double()
        feat_src = feat.double()

        if self._norm == 'both':
            norm_src = th.pow(src_degrees, -0.5)
            shp = norm_src.shape + (1,) * (feat.dim() - 1)
            norm_src = th.reshape(norm_src, shp).to(feat.device)
            feat_src = feat_src * norm_src

        if self._in_feats > self._out_feats:
            # mult W first to reduce the feature size for aggregation.
            feat_src = th.matmul(feat_src.double(), self.weight.double())
            rst = adj @ feat_src
        else:
            # aggregate first then mult W
            rst = adj @ feat_src
            rst = th.matmul(rst.double(), self.weight.double())

        if self._norm != 'none':
            if self._norm == 'both':
                norm_dst = th.pow(dst_degrees, -0.5)
            else: # right
                norm_dst = 1.0 / dst_degrees
            shp = norm_dst.shape + (1,) * (feat.dim() - 1)
            norm_dst = th.reshape(norm_dst, shp).to(feat.device)
            rst = rst * norm_dst

        if self.bias is not None:
            rst = rst + self.bias

        if self._activation is not None:
            rst = self._activation(rst)

        return rst


In [41]:
"""Torch Module for DenseSAGEConv"""
# pylint: disable= no-member, arguments-differ, invalid-name
from torch import nn
# from ....utils import check_eq_shape



# [docs]
class DenseSAGEConv1(nn.Module):
    
    def __init__(self,
                 in_feats,
                 out_feats,
                 feat_drop=0.,
                 bias=True,
                 norm=None,
                 activation=None):
        super().__init__()
        self._in_feats = in_feats
        self._out_feats = out_feats
        self._norm = norm
        self.feat_drop = nn.Dropout(feat_drop)
        self.activation = activation
        self.fc = nn.Linear(in_feats, out_feats, bias=bias).double()
        self.reset_parameters()


# [docs]
    def reset_parameters(self):
        
        gain = nn.init.calculate_gain('relu')
        nn.init.xavier_uniform_(self.fc.weight.double(), gain=gain)



# [docs]
    def forward(self, adj, feat):
        
#         check_eq_shape(feat)
        if isinstance(feat, tuple):
            feat_src = self.feat_drop(feat[0]).double()
            feat_dst = self.feat_drop(feat[1]).double()
        else:
            feat_src = feat_dst = self.feat_drop(feat.double())
        adj = adj.double().to(feat_src.device)
        in_degrees = adj.sum(dim=1, keepdim=True)
        h_neigh = (adj @ feat_src + feat_dst) / (in_degrees + 1)
        h_neigh=h_neigh.double()
        rst = self.fc(h_neigh.double())
        # activation
        if self.activation is not None:
            rst = self.activation(rst.double())
        # normalization
        if self._norm is not None:
            rst = self._norm(rst.double())

        return rst.double()


In [42]:
# from dgl.nn import GraphConv
# from dgl.nn import DenseGraphConv
# from dgl.nn import DenseSAGEConv
# from dgl.nn import GATConv

# class GCN(nn.Module):
#     def __init__(self, in_feats, h_feats1,h_feats2,h_feats3, num_classes):
#         super(GCN, self).__init__()
        
#         self.h_feats1=h_feats1
#         self.h_feats2=h_feats2
#         self.h_feats3=h_feats3
        
#         self.conv1 = DenseSAGEConv1(in_feats, h_feats1)
# #         self.conv2 = DenseSAGEConv1(in_feats, self.h_feats2)
# #         self.conv1_2=DenseSAGEConv1(h_feats1, h_feats1)
# #         self.conv1_3=DenseSAGEConv1(h_feats1, h_feats2)
# #         self.conv1_4=DenseSAGEConv1(self.h_feats2, self.h_feats3)
#         self.conv2 = DenseSAGEConv1(h_feats1, num_classes)
#         self.dequant = torch.ao.quantization.DeQuantStub()

#     def forward(self, g, in_feat):
#         h = self.conv1(g.adj().to_dense().double(),self.dequant(g.ndata['feat']).double())
#         h = F.relu(h)

# #         h=self.conv1_2(g.adj().to_dense().double(),h)
# #         h = F.relu(h)
        
# #         h=self.conv1_3(g.adj().to_dense(),h)
# #         h = F.relu(h)
        
# #         h=self.conv1_4(g.adj().to_dense(),h)
# #         h = F.relu(h)
        
#         h = self.conv2(g.adj().to_dense(), h)
#         g.ndata["h"] = h
#         return dgl.mean_nodes(g, "h")

# # g_model = GCN(200, 16, 2)

In [43]:
from dgl.nn import GraphConv
from dgl.nn import DenseGraphConv
from dgl.nn import DenseSAGEConv
from dgl.nn import GATConv

class GCN(nn.Module):
    def __init__(self, in_feats, h_feats1,h_feats2,h_feats3, num_classes):
        super(GCN, self).__init__()
        self.conv1 = GraphConv(in_feats, h_feats1)
#         self.conv2 = GraphConv(in_feats, h_feats2)
        self.conv1_2=GraphConv(h_feats1, h_feats1)
        self.conv1_3=GraphConv(h_feats1, h_feats2)
        self.conv1_4=GraphConv(h_feats2, h_feats3)
        self.conv2 = GraphConv(h_feats3, num_classes)

    def forward(self, g, in_feat):
        h = self.conv1(g, in_feat)
        h = F.relu(h)
#         print(h.shape)

#         h=self.conv1_2(g,h)
#         h = F.relu(h)
        
#         h=self.conv1_3(g,h)
#         h = F.relu(h)
        
#         h=self.conv1_4(g,h)
#         h = F.relu(h)
        
#         h = self.conv2(g, h)
        g.ndata["h"] = h
        return dgl.mean_nodes(g, "h")

# g_model = GCN(200, 16, 2)

In [44]:
from torch.utils.data.sampler import SubsetRandomSampler

from dgl.dataloading import GraphDataLoader

# num_examples = len(dataset)
# num_train = int(num_examples * 0.8)

# # train_sampler = SubsetRandomSampler(torch.arange(num_train))
# test_sampler = SubsetRandomSampler(torch.arange(num_train, num_examples))

train_dataloader = GraphDataLoader(
    train_dataset, batch_size=24, drop_last=False
)
test_dataloader = GraphDataLoader(
    test_dataset, batch_size=24, drop_last=False
)

In [45]:
def flat_accuracy(preds, labels):
    pred_flat = np.argmax(preds, axis=1).flatten()
    labels_flat = labels.flatten()
    return np.sum(pred_flat == labels_flat) / len(labels_flat)

In [46]:
from torch.optim.lr_scheduler import ReduceLROnPlateau

In [47]:
import transformers

In [48]:
import torch_geometric

In [49]:
from transformers import GraphormerForGraphClassification,GraphormerConfig
# from dgl.nn import GraphormerLayer

In [50]:
# batch_size = 16
# num_nodes = 25
# feat_size = 768
# num_heads = 8
# nfeat = torch.rand(batch_size, num_nodes, feat_size)
# # bias = torch.rand(batch_size, num_nodes, num_nodes, num_heads)
# model = GraphormerLayer(
#         feat_size=feat_size,
#         hidden_size=3,
#         num_heads=num_heads
#     )
# out = model(nfeat) #bias)

In [51]:
def final_layer(arr):
    arr=arr.cpu().detach().numpy()
    h_new=[]
    for i in range(1,arr.shape[0],25):
        h_new.append(arr[i])
    print(len)
    return (h_new)

In [52]:
class GCN(nn.Module):
    def __init__(self, in_feats, h_feats1,h_feats2,h_feats3, num_classes):
        super(GCN, self).__init__()
        self.conv1 = DenseGraphConv(in_feats, h_feats1)
#         self.conv2 = GraphConv(in_feats, h_feats2)
#         self.conv1_2=GraphConv(768, 100)
#         self.conv1_3=GraphConv(h_feats1, h_feats2)
#         self.conv1_4=GraphConv(h_feats2, h_feats3)
        
        self.conv2=DenseGraphConv(h_feats1, 2)
# self.conv2 = GraphConv(200, 2)
        

    def forward(self, g, in_feat):
#         test_dataset[0][0].ndata['feat']
#         print(g.ndata['feat'].shape)
        h = self.conv1(g.adj().to_dense().double(),g.ndata['feat'].float())
        h = F.relu(h)
#       

#         h=self.conv1_2(g,h)
#         h = F.relu(h)
        
#         h=self.conv1_3(g,h)
#         h = F.relu(h)
        
#         h=self.conv1_4(g,h)
#         h = F.relu(h)
        
        h = self.conv2(g.adj().to_dense().double(),h)
        g.ndata["h"] = h
        return dgl.mean_nodes(g, "h")

In [53]:
device=torch.device('cuda')

In [54]:
import dgl.function as fn

In [55]:
from dgl.nn import GlobalAttentionPooling

In [56]:
class Classifier_gen(nn.Module):
    def __init__(self, in_dim, hidden_dim_graph,hidden_dim1,n_classes,dropout,num_layers,pooling):
        super(Classifier_gen, self).__init__()
        if num_layers ==1:
            self.conv1 = GraphConv(in_dim, hidden_dim1)
        if num_layers==2:
            self.conv1 = GraphConv(in_dim, hidden_dim_graph)
            self.conv2 = GraphConv(hidden_dim_graph, hidden_dim1)
        if pooling == 'att':
            pooling_gate_nn = nn.Linear(hidden_dim1, 1)
            self.pooling = GlobalAttentionPooling(pooling_gate_nn)
        self.classify = nn.Sequential(nn.Linear(hidden_dim1,hidden_dim1),nn.Dropout(dropout))
        self.classify2 = nn.Sequential(nn.Linear(hidden_dim1, n_classes),nn.Dropout(dropout))
        self.out_act = nn.Sigmoid()
        self.num_layers = num_layers
        self.mypooling = pooling
    def forward(self, graph,feat, eweight=None):
        
        num_layers = self.num_layers
        pooling = self.mypooling
        h = feat.float()
        # Perform graph convolution and activation function.

        if eweight is None:
            graph.update_all(fn.copy_u('feat', 'm'), fn.sum('m', 'feat'))
            h = F.relu(self.conv1(graph, h))
        else:
            graph.edata['w'] = eweight
            graph.update_all(fn.u_mul_e('feat', 'w', 'm'), fn.sum('m', 'feat'))
            norm = self.w(g, graph.edata['w'])

            h = F.relu(self.conv1(graph, h,edge_weight=norm)) 

        

        if eweight is None:
            graph.update_all(fn.copy_u('feat', 'm'), fn.sum('m', 'feat'))
            h = F.relu(self.conv2(graph, h))
        else:
            graph.edata['w'] = eweight
            graph.update_all(fn.u_mul_e('feat', 'w', 'm'), fn.sum('m', 'feat'))
            norm = self.w(g, graph.edata['w'])

            h = F.relu(self.conv2(graph, h,edge_weight=norm)) 

        

            
        graph.ndata['h'] = h
        # Calculate graph representation by averaging all the node representations.
        #hg = dgl.mean_nodes(g, 'h')
        if pooling == "max":
            hg = dgl.max_nodes(graph, 'h')
        elif pooling=="mean":
            hg = dgl.mean_nodes(graph, 'h')
        elif pooling == "sum":
            hg = dgl.sum_nodes(graph, 'h') 
        elif pooling =='att':  
            # Calculate graph representation by averaging all the node representations.
            hg = self.pooling(graph,h) 
        
        
        a2=self.classify(hg)
        a3=self.classify2(a2)
        return self.out_act(a3)

In [66]:
# Create the model with given dimensions
train_loss_values = []
train_accuracy = []
val_loss_values = []
val_accuracy = []

model = Classifier_gen(768, hidden_dim_graph=100,hidden_dim1=100,n_classes=2,dropout=0.3,num_layers=2,pooling='att').to(device)
# model=GCN(768, 100, 1, 2, 0.3).to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
scheduler=ReduceLROnPlateau(optimizer,mode='min',patience=3)

for epoch in range(100):
    total_loss=0
    train_batch_accuracy = 0
    print("Epoch: ",epoch)
    epoch_loss=0
    epoch_acc=[]
    count=0
    for batched_graph, labels in train_dataloader:
        pred = model(batched_graph.to(device) ,batched_graph.ndata["feat"].float().to(device))    #.float())
        loss = F.cross_entropy(pred.to(device), labels.to(device))
#         print(count)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        epoch_loss+=loss
        batch_logits = pred
        logits = batch_logits.detach().cpu().numpy()
        label_ids = labels.to('cpu').numpy()
        train_batch_accuracy = flat_accuracy(logits, label_ids)
        epoch_acc.append(train_batch_accuracy)
        count+=1
#         print("Training Loss:", loss)
    scheduler.step(epoch_loss)
    print("Epoch Loss:" ,epoch_loss)
    print("epoch_accuracy:", np.array(epoch_acc).mean())



Epoch:  0
Epoch Loss: tensor(106.8908, device='cuda:0', grad_fn=<AddBackward0>)
epoch_accuracy: 0.8474187631027253
Epoch:  1
Epoch Loss: tensor(104.2264, device='cuda:0', grad_fn=<AddBackward0>)
epoch_accuracy: 0.8666797693920335
Epoch:  2
Epoch Loss: tensor(101.8746, device='cuda:0', grad_fn=<AddBackward0>)
epoch_accuracy: 0.8762447589098533
Epoch:  3
Epoch Loss: tensor(103.1444, device='cuda:0', grad_fn=<AddBackward0>)
epoch_accuracy: 0.8659591194968556
Epoch:  4
Epoch Loss: tensor(101.5224, device='cuda:0', grad_fn=<AddBackward0>)
epoch_accuracy: 0.8786687631027253
Epoch:  5
Epoch Loss: tensor(101.2764, device='cuda:0', grad_fn=<AddBackward0>)
epoch_accuracy: 0.8795204402515723
Epoch:  6
Epoch Loss: tensor(101.0869, device='cuda:0', grad_fn=<AddBackward0>)
epoch_accuracy: 0.8841719077568134
Epoch:  7
Epoch Loss: tensor(100.2415, device='cuda:0', grad_fn=<AddBackward0>)
epoch_accuracy: 0.8881682389937107
Epoch:  8
Epoch Loss: tensor(100.7020, device='cuda:0', grad_fn=<AddBackward0>)


Epoch Loss: tensor(97.2244, device='cuda:0', grad_fn=<AddBackward0>)
epoch_accuracy: 0.9046776729559749
Epoch:  73
Epoch Loss: tensor(97.1891, device='cuda:0', grad_fn=<AddBackward0>)
epoch_accuracy: 0.9098532494758911
Epoch:  74
Epoch Loss: tensor(96.8487, device='cuda:0', grad_fn=<AddBackward0>)
epoch_accuracy: 0.9133909853249476
Epoch:  75
Epoch Loss: tensor(97.7683, device='cuda:0', grad_fn=<AddBackward0>)
epoch_accuracy: 0.9074292452830188
Epoch:  76
Epoch Loss: tensor(97.0501, device='cuda:0', grad_fn=<AddBackward0>)
epoch_accuracy: 0.9091981132075472
Epoch:  77
Epoch Loss: tensor(97.5906, device='cuda:0', grad_fn=<AddBackward0>)
epoch_accuracy: 0.9045466457023063
Epoch:  78
Epoch Loss: tensor(96.9151, device='cuda:0', grad_fn=<AddBackward0>)
epoch_accuracy: 0.9089360587002097
Epoch:  79
Epoch Loss: tensor(97.1264, device='cuda:0', grad_fn=<AddBackward0>)
epoch_accuracy: 0.9091981132075472
Epoch:  80
Epoch Loss: tensor(97.3699, device='cuda:0', grad_fn=<AddBackward0>)
epoch_accur

In [93]:
model.eval()
num_correct = 0
num_tests = 0
test_labels=[]
predictions=[]
for batched_graph, labels in test_dataloader:
    pred = model(batched_graph.to(device), batched_graph.ndata["feat"].float().to(device))
    predictions+=(pred.argmax(1).cpu().numpy().tolist())
    test_labels+=(labels.tolist())
    num_correct += (pred.argmax(1) == labels.to(device)).sum().item()
    num_tests += len(labels)

print("Test accuracy:", num_correct / num_tests)

from sklearn.metrics import f1_score
def calculate_f1(pred,labels):
#     metric = BinaryF1Score(multidim_average='samplewise')
    return f1_score(labels, pred, average='macro')
f1_score=calculate_f1((np.array(predictions)),(np.array(test_labels)))

print("F1-Score: ", f1_score)

0.7023401286461131

In [138]:
"""Torch Module for GNNExplainer"""
# pylint: disable= no-member, arguments-differ, invalid-name
from math import sqrt
import torch

from torch import nn
from tqdm import tqdm

# from dgl.dataloading.base import NID, EID
# from dgl import khop_in_subgraph


# [docs]
class GNNExplainer(nn.Module):
    r"""GNNExplainer model from `GNNExplainer: Generating Explanations for
    Graph Neural Networks <https://arxiv.org/abs/1903.03894>`__

    It identifies compact subgraph structures and small subsets of node features that play a
    critical role in GNN-based node classification and graph classification.

    To generate an explanation, it learns an edge mask :math:`M` and a feature mask :math:`F`
    by optimizing the following objective function.

    .. math::
      l(y, \hat{y}) + \alpha_1 \|M\|_1 + \alpha_2 H(M) + \beta_1 \|F\|_1 + \beta_2 H(F)

    where :math:`l` is the loss function, :math:`y` is the original model prediction,
    :math:`\hat{y}` is the model prediction with the edge and feature mask applied, :math:`H` is
    the entropy function.

    Parameters
    ----------
    model : nn.Module
        The GNN model to explain.

        * The required arguments of its forward function are graph and feat.
          The latter one is for input node features.
        * It should also optionally take an eweight argument for edge weights
          and multiply the messages by it in message passing.
        * The output of its forward function is the logits for the predicted
          node/graph classes.

        See also the example in :func:`explain_node` and :func:`explain_graph`.
    num_hops : int
        The number of hops for GNN information aggregation.
    lr : float, optional
        The learning rate to use, default to 0.01.
    num_epochs : int, optional
        The number of epochs to train.
    alpha1 : float, optional
        A higher value will make the explanation edge masks more sparse by decreasing
        the sum of the edge mask.
    alpha2 : float, optional
        A higher value will make the explanation edge masks more sparse by decreasing
        the entropy of the edge mask.
    beta1 : float, optional
        A higher value will make the explanation node feature masks more sparse by
        decreasing the mean of the node feature mask.
    beta2 : float, optional
        A higher value will make the explanation node feature masks more sparse by
        decreasing the entropy of the node feature mask.
    log : bool, optional
        If True, it will log the computation process, default to True.
    """

    def __init__(self,
                 model,
                 num_hops,
                 lr=0.01,
                 num_epochs=100,
                 *,
                 alpha1=0.005,
                 alpha2=1.0,
                 beta1=1.0,
                 beta2=0.1,
                 log=True):
        super(GNNExplainer, self).__init__()
        self.model = model
        self.num_hops = num_hops
        self.lr = lr
        self.num_epochs = num_epochs
        self.alpha1 = alpha1
        self.alpha2 = alpha2
        self.beta1 = beta1
        self.beta2 = beta2
        self.log = log

    def _init_masks(self, graph, feat):
        r"""Initialize learnable feature and edge mask.

        Parameters
        ----------
        graph : DGLGraph
            Input graph.
        feat : Tensor
            Input node features.

        Returns
        -------
        feat_mask : Tensor
            Feature mask of shape :math:`(1, D)`, where :math:`D`
            is the feature size.
        edge_mask : Tensor
            Edge mask of shape :math:`(E)`, where :math:`E` is the
            number of edges.
        """
        num_nodes, feat_size = feat.size()
        num_edges = graph.num_edges()
        device = feat.device

        std = 0.1
        feat_mask = nn.Parameter(torch.randn(1, feat_size, device=device) * std)

        std = nn.init.calculate_gain('relu') * sqrt(2.0 / (2 * num_nodes))
        edge_mask = nn.Parameter(torch.randn(num_edges, device=device) * std)

        return feat_mask, edge_mask

    def _loss_regularize(self, loss, feat_mask, edge_mask):
        r"""Add regularization terms to the loss.

        Parameters
        ----------
        loss : Tensor
            Loss value.
        feat_mask : Tensor
            Feature mask of shape :math:`(1, D)`, where :math:`D`
            is the feature size.
        edge_mask : Tensor
            Edge mask of shape :math:`(E)`, where :math:`E`
            is the number of edges.

        Returns
        -------
        Tensor
            Loss value with regularization terms added.
        """
        # epsilon for numerical stability
        eps = 1e-15

        edge_mask = edge_mask.sigmoid()
        # Edge mask sparsity regularization
        loss = loss + self.alpha1 * torch.sum(edge_mask)
        # Edge mask entropy regularization
        ent = - edge_mask * torch.log(edge_mask + eps) - \
            (1 - edge_mask) * torch.log(1 - edge_mask + eps)
        loss = loss + self.alpha2 * ent.mean()

        feat_mask = feat_mask.sigmoid()
        # Feature mask sparsity regularization
        loss = loss + self.beta1 * torch.mean(feat_mask)
        # Feature mask entropy regularization
        ent = - feat_mask * torch.log(feat_mask + eps) - \
            (1 - feat_mask) * torch.log(1 - feat_mask + eps)
        loss = loss + self.beta2 * ent.mean()

        return loss


# [docs]
    def explain_node(self, node_id, graph, feat, **kwargs):
        r"""Learn and return a node feature mask and subgraph that play a
        crucial role to explain the prediction made by the GNN for node
        :attr:`node_id`.

        Parameters
        ----------
        node_id : int
            The node to explain.
        graph : DGLGraph
            A homogeneous graph.
        feat : Tensor
            The input feature of shape :math:`(N, D)`. :math:`N` is the
            number of nodes, and :math:`D` is the feature size.
        kwargs : dict
            Additional arguments passed to the GNN model. Tensors whose
            first dimension is the number of nodes or edges will be
            assumed to be node/edge features.

        Returns
        -------
        new_node_id : Tensor
            The new ID of the input center node.
        sg : DGLGraph
            The subgraph induced on the k-hop in-neighborhood of :attr:`node_id`.
        feat_mask : Tensor
            Learned feature importance mask of shape :math:`(D)`, where :math:`D` is the
            feature size. The values are within range :math:`(0, 1)`.
            The higher, the more important.
        edge_mask : Tensor
            Learned importance mask of the edges in the subgraph, which is a tensor
            of shape :math:`(E)`, where :math:`E` is the number of edges in the
            subgraph. The values are within range :math:`(0, 1)`.
            The higher, the more important.

        Examples
        --------

        >>> import dgl
        >>> import dgl.function as fn
        >>> import torch
        >>> import torch.nn as nn
        >>> from dgl.data import CoraGraphDataset
        >>> from dgl.nn import GNNExplainer

        >>> # Load dataset
        >>> data = CoraGraphDataset()
        >>> g = data[0]
        >>> features = g.ndata['feat']
        >>> labels = g.ndata['label']
        >>> train_mask = g.ndata['train_mask']

        >>> # Define a model
        >>> class Model(nn.Module):
        ...     def __init__(self, in_feats, out_feats):
        ...         super(Model, self).__init__()
        ...         self.linear = nn.Linear(in_feats, out_feats)
        ...
        ...     def forward(self, graph, feat, eweight=None):
        ...         with graph.local_scope():
        ...             feat = self.linear(feat)
        ...             graph.ndata['h'] = feat
        ...             if eweight is None:
        ...                 graph.update_all(fn.copy_u('h', 'm'), fn.sum('m', 'h'))
        ...             else:
        ...                 graph.edata['w'] = eweight
        ...                 graph.update_all(fn.u_mul_e('h', 'w', 'm'), fn.sum('m', 'h'))
        ...             return graph.ndata['h']

        >>> # Train the model
        >>> model = Model(features.shape[1], data.num_classes)
        >>> criterion = nn.CrossEntropyLoss()
        >>> optimizer = torch.optim.Adam(model.parameters(), lr=1e-2)
        >>> for epoch in range(10):
        ...     logits = model(g, features)
        ...     loss = criterion(logits[train_mask], labels[train_mask])
        ...     optimizer.zero_grad()
        ...     loss.backward()
        ...     optimizer.step()

        >>> # Explain the prediction for node 10
        >>> explainer = GNNExplainer(model, num_hops=1)
        >>> new_center, sg, feat_mask, edge_mask = explainer.explain_node(10, g, features)
        >>> new_center
        tensor([1])
        >>> sg.num_edges()
        12
        >>> # Old IDs of the nodes in the subgraph
        >>> sg.ndata[dgl.NID]
        tensor([ 9, 10, 11, 12])
        >>> # Old IDs of the edges in the subgraph
        >>> sg.edata[dgl.EID]
        tensor([51, 53, 56, 48, 52, 57, 47, 50, 55, 46, 49, 54])
        >>> feat_mask
        tensor([0.2638, 0.2738, 0.3039,  ..., 0.2794, 0.2643, 0.2733])
        >>> edge_mask
        tensor([0.0937, 0.1496, 0.8287, 0.8132, 0.8825, 0.8515, 0.8146, 0.0915, 0.1145,
                0.9011, 0.1311, 0.8437])
        """
        self.model.eval()
        num_nodes = graph.num_nodes()
        num_edges = graph.num_edges()

        # Extract node-centered k-hop subgraph and
        # its associated node and edge features.
        sg, inverse_indices = khop_in_subgraph(graph, node_id, self.num_hops)
        sg_nodes = sg.ndata[NID].long()
        sg_edges = sg.edata[EID].long()
        feat = feat[sg_nodes]
        for key, item in kwargs.items():
            if torch.is_tensor(item) and item.size(0) == num_nodes:
                item = item[sg_nodes]
            elif torch.is_tensor(item) and item.size(0) == num_edges:
                item = item[sg_edges]
            kwargs[key] = item

        # Get the initial prediction.
        with torch.no_grad():
            logits = self.model(graph=sg, feat=feat, **kwargs)
            pred_label = logits.argmax(dim=-1)

        feat_mask, edge_mask = self._init_masks(sg, feat)

        params = [feat_mask, edge_mask]
        optimizer = torch.optim.Adam(params, lr=self.lr)

        if self.log:
            pbar = tqdm(total=self.num_epochs)
            pbar.set_description('Explain node {node_id}')

        for _ in range(self.num_epochs):
            optimizer.zero_grad()
            h = feat * feat_mask.sigmoid()
            logits = self.model(graph=sg, feat=h,
                                eweight=edge_mask.sigmoid(), **kwargs)
            log_probs = logits.log_softmax(dim=-1)
            loss = -log_probs[inverse_indices, pred_label[inverse_indices]]
            loss = self._loss_regularize(loss, feat_mask, edge_mask)
            loss.backward()
            optimizer.step()

            if self.log:
                pbar.update(1)

        if self.log:
            pbar.close()

        feat_mask = feat_mask.detach().sigmoid().squeeze()
        edge_mask = edge_mask.detach().sigmoid()

        return inverse_indices, sg, feat_mask, edge_mask



# [docs]
    def explain_graph(self, graph, feat, **kwargs):
        r"""Learn and return a node feature mask and an edge mask that play a
        crucial role to explain the prediction made by the GNN for a graph.

        Parameters
        ----------
        graph : DGLGraph
            A homogeneous graph.
        feat : Tensor
            The input feature of shape :math:`(N, D)`. :math:`N` is the
            number of nodes, and :math:`D` is the feature size.
        kwargs : dict
            Additional arguments passed to the GNN model. Tensors whose
            first dimension is the number of nodes or edges will be
            assumed to be node/edge features.

        Returns
        -------
        feat_mask : Tensor
            Learned feature importance mask of shape :math:`(D)`, where :math:`D` is the
            feature size. The values are within range :math:`(0, 1)`.
            The higher, the more important.
        edge_mask : Tensor
            Learned importance mask of the edges in the graph, which is a tensor
            of shape :math:`(E)`, where :math:`E` is the number of edges in the
            graph. The values are within range :math:`(0, 1)`. The higher,
            the more important.

        Examples
        --------

        >>> import dgl.function as fn
        >>> import torch
        >>> import torch.nn as nn
        >>> from dgl.data import GINDataset
        >>> from dgl.dataloading import GraphDataLoader
        >>> from dgl.nn import AvgPooling, GNNExplainer

        >>> # Load dataset
        >>> data = GINDataset('MUTAG', self_loop=True)
        >>> dataloader = GraphDataLoader(data, batch_size=64, shuffle=True)

        >>> # Define a model
        >>> class Model(nn.Module):
        ...     def __init__(self, in_feats, out_feats):
        ...         super(Model, self).__init__()
        ...         self.linear = nn.Linear(in_feats, out_feats)
        ...         self.pool = AvgPooling()
        ...
        ...     def forward(self, graph, feat, eweight=None):
        ...         with graph.local_scope():
        ...             feat = self.linear(feat)
        ...             graph.ndata['h'] = feat
        ...             if eweight is None:
        ...                 graph.update_all(fn.copy_u('h', 'm'), fn.sum('m', 'h'))
        ...             else:
        ...                 graph.edata['w'] = eweight
        ...                 graph.update_all(fn.u_mul_e('h', 'w', 'm'), fn.sum('m', 'h'))
        ...             return self.pool(graph, graph.ndata['h'])

        >>> # Train the model
        >>> feat_size = data[0][0].ndata['attr'].shape[1]
        >>> model = Model(feat_size, data.gclasses)
        >>> criterion = nn.CrossEntropyLoss()
        >>> optimizer = torch.optim.Adam(model.parameters(), lr=1e-2)
        >>> for bg, labels in dataloader:
        ...     logits = model(bg, bg.ndata['attr'])
        ...     loss = criterion(logits, labels)
        ...     optimizer.zero_grad()
        ...     loss.backward()
        ...     optimizer.step()

        >>> # Explain the prediction for graph 0
        >>> explainer = GNNExplainer(model, num_hops=1)
        >>> g, _ = data[0]
        >>> features = g.ndata['attr']
        >>> feat_mask, edge_mask = explainer.explain_graph(g, features)
        >>> feat_mask
        tensor([0.2362, 0.2497, 0.2622, 0.2675, 0.2649, 0.2962, 0.2533])
        >>> edge_mask
        tensor([0.2154, 0.2235, 0.8325, ..., 0.7787, 0.1735, 0.1847])
        """
        self.model.eval()

        # Get the initial prediction.
        with torch.no_grad():
            logits = self.model(graph=graph, feat=feat, **kwargs)
            pred_label = logits.argmax(dim=-1)

        feat_mask, edge_mask = self._init_masks(graph, feat)

        params = [feat_mask, edge_mask]
        optimizer = torch.optim.Adam(params, lr=self.lr)

        if self.log:
            pbar = tqdm(total=self.num_epochs)
            pbar.set_description('Explain graph')

        for _ in range(self.num_epochs):
            optimizer.zero_grad()
            h = feat * feat_mask.sigmoid()
            logits = self.model(graph=graph, feat=h.float(),
                                eweight=edge_mask.sigmoid().float(), **kwargs)
            log_probs = logits.log_softmax(dim=-1)
            loss = -log_probs[0, pred_label[0]]
            loss = self._loss_regularize(loss, feat_mask, edge_mask)
            loss.backward()
            optimizer.step()

            if self.log:
                pbar.update(1)

        if self.log:
            pbar.close()

        feat_mask = feat_mask.detach().sigmoid().squeeze()
        edge_mask = edge_mask.detach().sigmoid()

        return feat_mask, edge_mask


In [139]:
# from dgl.nn import GNNExplainer

In [140]:
explainer = GNNExplainer(model, num_hops=1)

In [141]:
g1,label=train_dataset[0]

In [147]:
g, _ = train_dataset[0]
features = g.ndata['feat'].float()
feat_mask, edge_mask = explainer.explain_graph(g.to(device), features.to(torch.float32).to(device))




  0%|                                                                                          | 0/100 [00:00<?, ?it/s]


Explain graph:   0%|                                                                           | 0/100 [00:00<?, ?it/s]

DGLError: The node features' data type torch.float64 doesn't match edge features' data type torch.float32, please convert them to the same type.

In [122]:
feat_mask, edge_mask = explainer.explain_graph(g1,g1.ndata['feat'])

# tensor([1])

# 12
# # Old IDs of the nodes in the subgraph

# tensor([ 9, 10, 11, 12])
# # Old IDs of the edges in the subgraph

# tensor([51, 53, 56, 48, 52, 57, 47, 50, 55, 46, 49, 54])

# tensor([0.2638, 0.2738, 0.3039,  ..., 0.2794, 0.2643, 0.2733])


TypeError: forward() got an unexpected keyword argument 'graph'

In [102]:
feat_mask

NameError: name 'feat_mask' is not defined

In [ ]:
edge_mask